### ISSUE TITLE
[BUG] Exception when trying to decode tlv id for ruuvi packets

### ISSUE THREAD

**Issue by PFigs** [wirepas/backend-client#166]
Backend client v1.2.x is throwing exceptions in the command line when trying to parse ruuvi packets.

14:25.46 | wm-gw-cli > nodesException in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/paho/mqtt/client.py", line 2913, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/paho/mqtt/client.py", line 1578, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/paho/mqtt/client.py", line 1072, in loop
    rc = self.loop_read(max_packets)
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/paho/mqtt/client.py", line 1374, in loop_read
    rc = self._packet_read()
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/paho/mqtt/client.py", line 2071, in _packet_read
    rc = self._packet_handle()
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/paho/mqtt/client.py", line 2560, in _packet_handle
    return self._handle_publish()
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/paho/mqtt/client.py", line 2759, in _handle_publish
    self._handle_on_message(message)
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/paho/mqtt/client.py", line 2902, in _handle_on_message
    callback(self, self._userdata, message)
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/wirepas_backend_client/api/mqtt/decorators.py", line 29, in wrapper_retrieve_message
    ).from_bus(message.payload)
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/wirepas_backend_client/messages/generic.py", line 88, in from_bus
    return cls.from_proto(d)
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/wirepas_backend_client/messages/generic.py", line 99, in from_proto
    obj = cls.from_payload(proto)
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/wirepas_messaging/gateway/api/received_data.py", line 110, in from_payload
    hop_count=hop_count,
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/wirepas_backend_client/messages/ruuvi.py", line 69, in __init__
    self.decode()
  File "/home/pi/.virtualenvs/backend_120/lib/python3.7/site-packages/wirepas_backend_client/messages/ruuvi.py", line 131, in decode
    tlv_name = self.TYPES[tlv_id]["name"]
KeyError: 77

Backend client v. 1.2.1:

14:33.21 | wm-gw-cli > Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/paho/mqtt/client.py", line 2913, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/paho/mqtt/client.py", line 1578, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/paho/mqtt/client.py", line 1072, in loop
    rc = self.loop_read(max_packets)
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/paho/mqtt/client.py", line 1374, in loop_read
    rc = self._packet_read()
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/paho/mqtt/client.py", line 2071, in _packet_read
    rc = self._packet_handle()
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/paho/mqtt/client.py", line 2560, in _packet_handle
    return self._handle_publish()
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/paho/mqtt/client.py", line 2759, in _handle_publish
    self._handle_on_message(message)
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/paho/mqtt/client.py", line 2902, in _handle_on_message
    callback(self, self._userdata, message)
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/wirepas_backend_client/api/mqtt/decorators.py", line 29, in wrapper_retrieve_message
    ).from_bus(message.payload)
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/wirepas_backend_client/messages/generic.py", line 88, in from_bus
    return cls.from_proto(d)
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/wirepas_backend_client/messages/generic.py", line 99, in from_proto
    obj = cls.from_payload(proto)
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/wirepas_messaging/gateway/api/received_data.py", line 110, in from_payload
    hop_count=hop_count,
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/wirepas_backend_client/messages/ruuvi.py", line 69, in __init__
    self.decode()
  File "/home/pi/.virtualenvs/backend_121/lib/python3.7/site-packages/wirepas_backend_client/messages/ruuvi.py", line 131, in decode
    tlv_name = self.TYPES[tlv_id]["name"]
KeyError: 84

gateway_configuration
requesting configuration for 202481587086731
got no reply for 202481587086731
14:33.44 | wm-gw-cli > list
[]
14:33.47 | wm-gw-cli >

**Comment by PFigs** [comment]
Could not replicate issues under 1.2.1 or 1.2.0. Likely to be an apdu syntax. Will proceed by acquiring and ignoring decoding errors.
