### ISSUE TITLE
SSL support (self-signed)

### ISSUE THREAD

**Issue by opoei** [wirepas/backend-client#170]
### Problem
As is it does not appear that the client supports communications to secure transports.
For the sake of demonstration, I've added the self signed cert to the correct path and have verified that ssl works on the defined port (8883).  However the client is still erroring with:

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wirepas/.local/lib/python3.7/site-packages/wirepas_backend_client/api/mqtt/handlers.py", line 177, in run
    self.mqtt.serve()
  File "/home/wirepas/.local/lib/python3.7/site-packages/wirepas_backend_client/api/mqtt/connectors.py", line 141, in serve
    self.connect()
  File "/home/wirepas/.local/lib/python3.7/site-packages/wirepas_backend_client/api/mqtt/connectors.py", line 192, in connect
    self.hostname, port=self.port, keepalive=self.keep_alive
  File "/home/wirepas/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/home/wirepas/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 994, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)
```

**Comment by PFigs** [comment]
Hi @opoei!

Could you please elaborate on your setup? From what I understand you are trying to connect to a remote MQTT broker where you have setup its TLS connection using self singed certificates.

On the client side, it is not so clear what you re doing. Have you whitelisted your self signed certificate at the host level? How are you calling/starting the backend client example(s)?

**Comment by opoei** [comment]
I resolved it by including the following in the dockerfile `container/slim/Dockerfile`

```
USER root
ADD self-signed-certs/wirepas_bundle.crt /usr/local/share/ca-certificates/client_bundle.crt
RUN update-ca-certificates
```
