### ISSUE TITLE
[BUG] Data processing exception.

### ISSUE THREAD

**Issue by ErkkiSalonenW** [wirepas/backend-client#287]
When running tests, it could happen that incoming data refers to key that does not yet exists. See log below

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wirepas/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3428, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/wirepas/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1782, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/wirepas/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1177, in loop
    rc = self.loop_read(max_packets)
  File "/home/wirepas/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1568, in loop_read
    rc = self._packet_read()
  File "/home/wirepas/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2315, in _packet_read
    rc = self._packet_handle()
  File "/home/wirepas/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2952, in _packet_handle
    return self._handle_publish()
  File "/home/wirepas/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3228, in _handle_publish
    self._handle_on_message(message)
  File "/home/wirepas/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3416, in _handle_on_message
    callback(self, self._userdata, message)
  File "/home/wirepas/.local/lib/python3.7/site-packages/wirepas_backend_client/api/mqtt/decorators.py", line 48, in wrapper_retrieve_message
    f(message.payload, topic)
  File "/home/wirepas/.local/lib/python3.7/site-packages/wirepas_backend_client/test/kpi_mesh.py", line 157, in on_response_cb
    if int(config["network_address"]) == int(network_id):
KeyError: 'network_address'
2020-03-19 00:04:45,353 | [INFO] test_kpi@http.py:176: HTTP status_msg receiver running
2020-03-19 00:05:45,354 | [INFO] test_kpi@http.py:176: HTTP status_msg receiver running
2020-03-19 00:06:45,355 | [INFO] test_kpi@http.py:176: HTTP status_msg receiver running
2020-03-19 00:07:45,356 | [INFO] test_kpi@http.py:176: HTTP status_msg receiver running
2020-03-19 00:08:45,357 | [INFO] test_kpi@http.py:176: HTTP status_msg receiver running
2020-03-19 00:09:45,357 | [INFO] test_kpi@http.py:176: HTTP status_msg receiver running

**Comment by ErkkiSalonenW** [comment]
Added function self.isValidNetworkId(network_id) that checks if address is valid. If not, message is skipped.
