### ISSUE TITLE
[BUG] install from git fails

### ISSUE THREAD

**Issue by jbpspl** [wirepas/backend-client#339]
**Describe the bug**
install fails after checking out git head, v1.3.6 and 1.3.5 (and possibly earlier). Complains about not finding mysql_config.

**Expected behavior
cloned repo, followed instructions, should install correctly without complaining. 

**To Reproduce**
1. clone repo (git clone yadda yadda...)

2. pip3 install . (after installing pip, please include in install requirements)

3: install output:
```
git checkout v1.3.5
Previous HEAD position was 26bf2a3 Release v1.3.6
HEAD is now at 74f366a Release v1.3.5
jelle@ubunu2004:~/backend-client$ pip3 install .
Processing /home/jelle/backend-client
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting wirepas-messaging==1.3.0
  Using cached wirepas_messaging-1.3.0-py3-none-any.whl (1.6 MB)
Collecting influxdb==5.2.3
  Using cached influxdb-5.2.3-py2.py3-none-any.whl (73 kB)
Collecting mysqlclient==1.4.6
  Using cached mysqlclient-1.4.6.tar.gz (85 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-luu6zx2x/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-luu6zx2x/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-luu6zx2x/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-luu6zx2x/mysqlclient/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-luu6zx2x/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-luu6zx2x/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-luu6zx2x/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
4. See error: ? (there is a similar issue from feb 2020 i think? tbd.

**Software versions:**
 - OS: ubuntu 20.04 tls in virtual box
 - Python version: 3.8

**Comment by jbpspl** [comment]
Never mind, missed the default-libmysqlclient-dev step. build still fails though, probably python3.8 != python3.7

**Comment by ErkkiSalonenW** [comment]
Hi. Current version tested is Python 3.7. Need to check this 3.8 anyway.
